//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscUtils {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscUtils.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;value&gt;
        ///  &lt;struct&gt;
        ///    &lt;member&gt;
        ///      &lt;name&gt;version&lt;/name&gt;
        ///      &lt;value&gt;
        ///        &lt;struct&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;hostname&lt;/name&gt;
        ///            &lt;value&gt;cheesy-2&lt;/value&gt;
        ///          &lt;/member&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;date&lt;/name&gt;
        ///            &lt;value&gt;2008-11-08&lt;/value&gt;
        ///          &lt;/member&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;product_version&lt;/name&gt;
        ///            &lt;value&gt;1.0.0&lt;/value&gt;
        ///          &lt;/member&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;product_brand&lt;/name&gt;
        ///            &lt;va [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string XVA_ova_base {
            get {
                return ResourceManager.GetString("XVA_ova_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на                               &lt;value&gt;{0}&lt;/value&gt;
        ///.
        /// </summary>
        internal static string XVA_ova_ref {
            get {
                return ResourceManager.GetString("XVA_ova_ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на             &lt;value&gt;
        ///              &lt;struct&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;class&lt;/name&gt;
        ///                  &lt;value&gt;SR&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;id&lt;/name&gt;
        ///                  &lt;value&gt;{0}&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;snapshot&lt;/name&gt;
        ///                  &lt;value&gt;
        ///                    &lt;struct&gt;
        ///                      &lt;member&gt;
        ///                        &lt;name&gt;uuid&lt;/name&gt;
        ///               [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string XVA_ova_sr {
            get {
                return ResourceManager.GetString("XVA_ova_sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на             &lt;value&gt;
        ///              &lt;struct&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;class&lt;/name&gt;
        ///                  &lt;value&gt;VBD&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;id&lt;/name&gt;
        ///                  &lt;value&gt;{0}&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;snapshot&lt;/name&gt;
        ///                  &lt;value&gt;
        ///                    &lt;struct&gt;
        ///                      &lt;member&gt;
        ///                        &lt;name&gt;uuid&lt;/name&gt;
        ///              [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string XVA_ova_vbd {
            get {
                return ResourceManager.GetString("XVA_ova_vbd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на             &lt;value&gt;
        ///              &lt;struct&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;class&lt;/name&gt;
        ///                  &lt;value&gt;VDI&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;id&lt;/name&gt;
        ///                  &lt;value&gt;{0}&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;snapshot&lt;/name&gt;
        ///                  &lt;value&gt;
        ///                    &lt;struct&gt;
        ///                      &lt;member&gt;
        ///                        &lt;name&gt;uuid&lt;/name&gt;
        ///              [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string XVA_ova_vdi {
            get {
                return ResourceManager.GetString("XVA_ova_vdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на             &lt;value&gt;
        ///              &lt;struct&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;class&lt;/name&gt;
        ///                  &lt;value&gt;VM&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;id&lt;/name&gt;
        ///                  &lt;value&gt;{0}&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;snapshot&lt;/name&gt;
        ///                  &lt;value&gt;
        ///                    &lt;struct&gt;
        ///                      &lt;member&gt;
        ///                        &lt;name&gt;uuid&lt;/name&gt;
        ///               [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string XVA_ova_vm {
            get {
                return ResourceManager.GetString("XVA_ova_vm", resourceCulture);
            }
        }
    }
}
